# Generated by Django 5.1.1 on 2024-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
